services:
  backend:
    build: ./backend
    container_name: lernix-backend
    ports:
      - '8000:8000'
    env_file:
      - ./backend/.env
    restart: always
  
  frontend:
    build: ./frontend
    container_name: lernix-frontend
    ports:
      - '5173:5173'
    environment:
      - VITE_API_BASE_URL=http://backend:8080
    depends_on:
      - backend
    restart: always